trigger:
  branches:
    include:
      - master
      - initial
      - azure-pipelines-latest

pool:
  vmImage: ubuntu-latest

variables:
  AngularDirectory: "src"

steps:
  - task: Npm@1
    displayName: "Restore NPM Packages"
    inputs:
      command: ci
      workingDir: $(AngularDirectory)

  - task: Npm@1
    displayName: "Install Angular cli"
    inputs:
      command: "custom"
      customCommand: "install -g @angular/cli"

  - task: Npm@1
    displayName: "npm build"
    inputs:
      command: custom
      customCommand: "run build -- --configuration production"
      workingDir: $(AngularDirectory)

  - task: CmdLine@2
    displayName: "Run Angular tests"
    inputs:
      script: "ng test --browsers=ChromeHeadless --code-coverage --watch=false"
